/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Kayttoliittyma;

import Kortisto.Kortisto;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.WindowConstants;

/**
 *
 * @author heidi
 */
public class Hakuikkuna extends javax.swing.JFrame {

    Kortisto kortisto;
    DefaultListModel model;
    String etu;
    String suku;
    String taito;
    Henkiloikkuna henkilo;
    /**
     * Creates new form Hakuikkuna
     */
    public Hakuikkuna() {
        initComponents();
    }

    public Hakuikkuna(Kortisto kortisto) {
        initComponents();
        this.kortisto = kortisto;
        model = new DefaultListModel();
        haetutLista.setModel(model);
        poistaButton.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etunimi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sukunimi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        taitoKentta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        haeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        haetutLista = new javax.swing.JList();
        poistaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAITAJA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hae henkilöitä nimen tai taidon perusteella", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        etunimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etunimiActionPerformed(evt);
            }
        });

        jLabel1.setText("Etunimi:");

        jLabel2.setText("Sukunimi:");

        sukunimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sukunimiActionPerformed(evt);
            }
        });

        jLabel3.setText("Taito:");

        taitoKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taitoKenttaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("ja/tai");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel5.setText("tai");

        haeButton.setText("Hae");
        haeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeButtonActionPerformed(evt);
            }
        });

        haetutLista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        haetutLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                haetutListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(haetutLista);

        poistaButton.setText("Poista valittu henkilö");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(taitoKentta)
                            .add(sukunimi)
                            .add(etunimi)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .add(108, 108, 108))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(47, 47, 47)
                                .add(haeButton))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(80, 80, 80)
                                .add(jLabel5))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(68, 68, 68)
                                .add(jLabel4)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(63, 63, 63)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(poistaButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etunimi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel4)
                        .add(7, 7, 7)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sukunimi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(33, 33, 33)
                        .add(jLabel5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(taitoKentta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(haeButton)
                    .add(poistaButton))
                .add(24, 24, 24))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void haeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeButtonActionPerformed
        etu = etunimi.getText();
        suku = sukunimi.getText();
        taito = taitoKentta.getText();
        ArrayList<String> haetut = kortisto.hae(etu, suku, taito);
        String[] haetutTaulukko = new String[haetut.size()];
        for (int i=0; i<haetut.size(); i++) {
            haetutTaulukko[i] = haetut.get(i);
        }
        haetutLista.setListData(haetutTaulukko);
        etunimi.setText("");
        sukunimi.setText("");
        taitoKentta.setText("");
    }//GEN-LAST:event_haeButtonActionPerformed

    private void haetutListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_haetutListaMouseClicked
        if (evt.getClickCount() == 1) {
            poistaButton.setVisible(true);
        }
        else if (evt.getClickCount() == 2) {
            String valittu = (String)haetutLista.getSelectedValue();
            henkilo = new Henkiloikkuna(kortisto, valittu);
            //ikkuna.setSize(450, 400);
            henkilo.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            henkilo.setVisible(true);
        }
    }//GEN-LAST:event_haetutListaMouseClicked

    private void etunimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etunimiActionPerformed
        etu = etunimi.getText();
        suku = sukunimi.getText();
        taito = taitoKentta.getText();
        ArrayList<String> haetut = kortisto.hae(etu, suku, taito);
        String[] haetutTaulukko = new String[haetut.size()];
        for (int i=0; i<haetut.size(); i++) {
            haetutTaulukko[i] = haetut.get(i);
        }
        haetutLista.setListData(haetutTaulukko);
        etunimi.setText("");
        sukunimi.setText("");
        taitoKentta.setText("");
    }//GEN-LAST:event_etunimiActionPerformed

    private void sukunimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sukunimiActionPerformed
        etu = etunimi.getText();
        suku = sukunimi.getText();
        taito = taitoKentta.getText();
        ArrayList<String> haetut = kortisto.hae(etu, suku, taito);
        String[] haetutTaulukko = new String[haetut.size()];
        for (int i=0; i<haetut.size(); i++) {
            haetutTaulukko[i] = haetut.get(i);
        }
        haetutLista.setListData(haetutTaulukko);
        etunimi.setText("");
        sukunimi.setText("");
        taitoKentta.setText("");
    }//GEN-LAST:event_sukunimiActionPerformed

    private void taitoKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taitoKenttaActionPerformed
        etu = etunimi.getText();
        suku = sukunimi.getText();
        taito = taitoKentta.getText();
        ArrayList<String> haetut = kortisto.hae(etu, suku, taito);
        String[] haetutTaulukko = new String[haetut.size()];
        for (int i=0; i<haetut.size(); i++) {
            haetutTaulukko[i] = haetut.get(i);
        }
        haetutLista.setListData(haetutTaulukko);
        etunimi.setText("");
        sukunimi.setText("");
        taitoKentta.setText("");
    }//GEN-LAST:event_taitoKenttaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hakuikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hakuikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hakuikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hakuikkuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Hakuikkuna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etunimi;
    private javax.swing.JButton haeButton;
    private javax.swing.JList haetutLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton poistaButton;
    private javax.swing.JTextField sukunimi;
    private javax.swing.JTextField taitoKentta;
    // End of variables declaration//GEN-END:variables
}
